# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "I don't have imposter syndrom, I'm just an imposter" and other thoughts
I tend to keep to myself
email: hwheelen@princeton.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Hannah, a so called "mathematician" working towards voting righs reform.
  I'm the data specialist for the Princeton Gerrymandering Project, which is a
  way of saying my day to day work is always  different, but it always has to
  do with data. Usually, I'm working with precinct level election data and the
  maps of these precincts that match. I'll record noteworthy things here, mostly
  for myself, but I'll put ut out there. I come across interesting data weird-ness
  and creative solutions to nice problems that you might have, since you've
  taken the time to read this far. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hananawa222
github_username:  hwheelen

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
